### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by ThomasBleijendaal** [ThomasBleijendaal/MicroFrontendPoC#1]
- [ ] Test with published artifacts
- [x] Clean up assembly loading
- [x] Lazy load root component
- [x] Root component should implement interface
- [x] Handle authentication
- [ ] Debug service via small bootstrapper
- [x] Support templated urls
- [ ] Support prefixing links automatically
- [ ] Support custom DI per dll

**Comment by ThomasBleijendaal** [comment]
DI is problematic
